# Generated by Django 3.2.19 on 2024-02-01 15:34

from django.db import migrations, models
import websiteapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=websiteapp.models.getfilename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
