# Generated by Django 5.0.1 on 2024-02-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobileno', models.IntegerField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('eventtype', models.CharField(max_length=150)),
                ('noofattendees', models.IntegerField(max_length=150)),
                ('dateofevent', models.DateField(max_length=150)),
                ('eventlocation', models.CharField(max_length=150)),
            ],
        ),
    ]
