# Generated by Django 5.0.1 on 2024-02-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0003_alter_booking_mobileno_alter_booking_noofattendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobileno',
            field=models.BigIntegerField(),
        ),
    ]
